context:
  name: "shs-libcxi"
  version: "14.0.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  - url: https://github.com/HewlettPackard/shs-libcxi/archive/refs/tags/release/shs-${{ version }}.tar.gz
    sha256: 7f47b7982aa3e68c092e74d432aac98d841f9982fb8e777e0599d9ccfafb3e76  # 14.0.1
#   sha256: fa5fe09e0ef5731930796d818f2449d368d50b8029991ed9038fb7ec4c3df00a  # 14.0.0
    patches:
      - fix-random.patch
      - fix-udp-header.patch
      - fix-fuse3-configure.patch
      - fix-fuse3-stats.patch
      - fix-fuse3-rh.patch
      - fix-i2c-ioctl.patch

build:
  number: 1
  script: build.sh
  skip:
    - win
    - osx

requirements:
  run_exports:
    - ${{ pin_subpackage('shs-libcxi', upper_bound='x') }}
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - autoconf
    - automake
    - libtool
    - make
    - pkg-config
  host:
    - libconfig
    - libfuse >=3
    - libnl
    - libnuma
    - libsystemd0
    - libuv
    - lm-sensors
    - shs-cassini-headers >=14.0.1
    - shs-cxi-drivers >=14.0.1
    - yaml

tests:
  - script:
      - test -f $PREFIX/lib/libcxi.so
      - test -f $PREFIX/include/libcxi/libcxi.h

about:
  homepage: https://github.com/HewlettPackard/shs-libcxi
  license: LGPL-2.1-only OR BSD-3-Clause
  license_file: cray-libcxi.spec
  summary: 'Library for CXI (Cassini eXtended Interface)'
  description: |
    Provides a userspace library for interacting with CXI hardware.

extra:
  recipe-maintainers:
    - j34ni
